### ISSUE TITLE
【産総研】【要対応】初期化をしていない変数の利用(moveit_core)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#10]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.STACK.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_core(distance_field)

指摘が出ている変数の初期化を行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
