### ISSUE TITLE
【産総研】【要対応】コンストラクタで初期化をしていない変数の利用(moveit_planners)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#11]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_planners(chomp_motion_planner)

指摘が出ている変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
