### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード(moveit_planners)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#12]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.MUST,NPD.FUNC.CALL.MUST
- 指摘重要度:重大
- パッケージ:moveit_planners(chomp_motion_planner)

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックする。 あるいは、指摘箇所で呼ばれている関数内でNULLチェックする。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
