### ISSUE TITLE
【産総研】【要対応】初期化をしていない変数の利用(moveit_planners)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#13]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.STACK.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_planners(ompl)

指摘が出ている変数の初期化を行う。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
