### ISSUE TITLE
【産総研】【要対応】逆参照される可能性のあるポインタ変数(moveit_ros)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#15]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:RNPD.DEREF,NPD.CHECK.MIGHT,NPD.GEN.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_ros(visualization,perception)

逆参照される可能性のあるポインタ変数をNULLチェックする。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
