### ISSUE TITLE
【産総研】【要対応】コンストラクタで初期化をしていない変数の利用(moveit_ros)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#16]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_ros(visualization)

指摘が出ている変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
