### ISSUE TITLE
【産総研】【要対応】初期化をしていない変数の利用(moveit_ros)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#17]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.STACK.MUST,UNINIT.STACK.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_ros(perception,warehouse,robot_interaction)

指摘が出ている変数の初期化を行う。 あるいは、未初期化の変数が利用されないようにする。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
