### ISSUE TITLE
【産総研】【要対応】NULL参照の可能性のあるコード(moveit_ros)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#19]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.CALL.MUST
- 指摘重要度:重大
- パッケージ:moveit_ros(planning_interface)

NULLポインタが返却される可能性のある関数の戻り値、パラメータをNULLチェックする。 あるいは、指摘箇所で呼ばれている関数内でNULLチェックする。

**Comment by k-hazama-esol** [comment]
PR #32 で修正済

**Comment by r-kurose** [comment]
レビュー結果の確認完了
