### ISSUE TITLE
【産総研】【要対応】初期値0の変数による除算の可能性

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#2]
- 指摘カテゴリ:ゼロ除算の可能性
- チェッカー:DBZ.GENERAL 
- 指摘重要度:重大
- パッケージ:moveit_plannners,moveit_kinematics

それぞれ除数となる変数が0の時、除算を行わないようにしている。
moveit_planners内のケースでは呼び出し先の関数でチェックを行い、0の場合returnしている。
moveit_kinematics内のケースでは変数が0の場合ROS_WARNを表示するようにしている

**Comment by r-kurose** [comment]
レビュー結果の確認完了
