### ISSUE TITLE
【産総研】【要対応】NULL参照をする可能性のあるコード(moveit_kinematics)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#3]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.MUST
- 指摘重要度:重大
- パッケージ:moveit_kinematics(kdl_kinematics_plugin,lma_kinematics_plugin)

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックする。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
