### ISSUE TITLE
【産総研】【要対応】newによって確保したリソースの解放漏れ(moveit_setup_assistant)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#36]
- 指摘カテゴリ:メモリリーク
- チェッカー:MLK.MUST
- 指摘重要度:エラー
- パッケージ:moveit_setup_assistant(widgets)

newで確保した変数が必要なくなる時点で、deleteによってリソースを解放する。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
