### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ(moveit_setup_assistant)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#37]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MUST
- 指摘重要度:エラー
- パッケージ:moveit_setup_assistant(widgets,tools)

指摘が出ているメンバ変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
