### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ(moveit_kinematics)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#39]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MIGHT
- 指摘重要度:エラー
- パッケージ:
moveit_kinematics(srv_kinematics_plugin,lma_kinematics_plugin,kdl_kinematics_plugin,ik_cache,cached_ik_kinematics,cached_ik_kinematics_plugin)

指摘が出ているメンバ変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
