### ISSUE TITLE
【産総研】【要対応】未初期化のデータの使用(moveit_kinematics)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#4]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.STACK.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_kinematics(cached_ik_kinematics_plugin)

指摘が出ている変数の初期化を行う。

**Comment by r-kurose** [comment]
レビュー結果の確認完了 及び PR の Q/A 完了
