### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ(moveit_core)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#40]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MUST
- 指摘重要度:エラー
- パッケージ:
moveit_core(robot_state,kinematic_constraints,dynamics_solver,distance_field,constraint_samplers)

指摘が出ているメンバ変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
