### ISSUE TITLE
【産総研】【要対応】無限ループ

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#41]
- 指摘カテゴリ:グローバル変数を持つ無限ループ
- チェッカー:INFINITE_LOOP.GLOBAL
- 指摘重要度:エラー
- パッケージ:moveit_ros(planning_interface,planning,perception)

ループ条件に用いられている変数が、ループ内で変化しない場合このエラーが出る。
実際はループが存在する関数ではない箇所で、ループ条件の変数が変更されている。
以下に一例としてplanning_interface/move_group_interface/src/move_group_interface.cpp の指摘を記載する。
```
std::vector<std::string> getKnownConstraints() const
{
  while (initializing_constraints_)
   {
       static ros::WallDuration d(0.01);
       d.sleep();
  }
```
これを解決するために、ループ条件に該当する変数にvolatile修飾子を付け、コンパイラの最適化を回避する。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
