### ISSUE TITLE
【産総研】【要対応】newによって確保したリソースの解放漏れ(moveit_ros)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#42]
- 指摘カテゴリ:メモリリークの可能性
- チェッカー:MLK.MIGHT
- 指摘重要度:エラー
- パッケージ:moveit_ros(planning)

return処理の前にdeleteを行い、メモリを解放する

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
