### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ(moveit_plugins)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#43]
- 指摘カテゴリ:未初期化のデータの使用
- チェッカー:UNINIT.CTOR.MUST
- 指摘重要度:エラー
- パッケージ:moveit_setup_plugins

指摘が出ているメンバ変数の初期化をコンストラクタで行う。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
