### ISSUE TITLE
【産総研】【要対応】メンバ変数の初期化漏れ(FilterJob())

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#46]
- 指摘カテゴリ:コンストラクタにおける未初期化の変数
- チェッカー:UNINIT.CTOR.MUST
- 指摘重要度:エラー
- 対象ソース:moveit_ros/perception/mesh_filter/include/moveit/mesh_filter/filter_job.h
```
89 template <typename ReturnType>
90 class FilterJob : public Job
91 {
92 public:
93   FilterJob(const boost::function<ReturnType()>& exec) : Job(), exec_(exec)
94   {
95   }
96   virtual void execute();
97   const ReturnType& getResult() const;
98  
99 private:
100   boost::function<ReturnType()> exec_;
101   ReturnType result_;
102 };
```
FilterJobクラスのコンストラクタでresult_を初期化していないため指摘が出ている。89行目および101行目よりresult_はテンプレート型で定義されている。よって初期値を一意に決めることができない。
```
115 template <typename ReturnType>
116 const ReturnType& FilterJob<ReturnType>::getResult() const
117 {
118   wait();
119   return result_;
120 }
```
上記118行目よりresult_はwait()を処理した後に参照される。
```
70 void Job::wait() const
71 {
72   boost::unique_lock<boost::mutex> lock(mutex_);
73   while (!done_)
74     condition_.wait(lock);
75 }
```
wait()の実装の73行目よりdone_ = falseの時、待機状態になる。
```
55 public:
56   Job() : done_(false)
57   {
58   }
```
FilterJobはJobクラスを継承しており、Jobのコンストラクタよりdone_ = falseとして初期化される。
```
104 template <typename ReturnType>
105 void FilterJob<ReturnType>::execute()
106 {
107   boost::unique_lock<boost::mutex> lock(mutex_);
108   if (!done_)  // not canceled !
109     result_ = exec_();
110  
111   done_ = true;
112   condition_.notify_all();
113 }
```
109行目よりexecute()にて(!doneの場合)result_にexec_()の戻り値を代入しdoneをtrueに設定する。
以上のことから、getResult()の119行目はexecute()の実行後にのみ実行される。よってreturn_が未初期化の状態で使用されることはないと考えられるので、修正の必要はない。

**Comment by r-kurose** [comment]
2020-01-23 の打ち合わせより、以下を試みる。
(1) non-type template parameter で対応する
(2) ReturnType() で初期化する

その他の案：
 コンストラクターに初期値引数を追加する。(デフォルトコンストラクターは = delete)

**Comment by r-kurose** [comment]
@KazukiHazama 
上記コメントを参考にしてみてください。

**Comment by k-hazama-esol** [comment]
上記コメントを参考に修正を行ったところ、(2)の修正方法で指摘が消えたことを確認しました。
```
93   FilterJob(const boost::function<ReturnType()>& exec) : Job(), exec_(exec)
94   {
95   }
↓
93   FilterJob(const boost::function<ReturnType()>& exec) : Job(), exec_(exec), result_(ReturnType())
94   {
95   }
```
こちらの修正で問題なければ、PRとして提出します。

**Comment by r-kurose** [comment]
この戻り値が使われるパターンが不正なシーケンスを踏んだ場合であるならば、戻り値はエラー値になる方が良いと思います。
ただし、既存の使用箇所で適切な戻り値(エラーコード)が無いかもしれません。その場合は、この修正で良いと思います。

**Comment by k-hazama-esol** [comment]
filter_job.hの既存の使用箇所について調べたところ、以下のソースでのみ使用されていました。
moveit_ros/perception/mesh_filter/src/mesh_filter_base.cpp
また、`getResult()`の使用箇所も下記のみでした。
```
195	void mesh_filter::MeshFilterBase::removeMesh(MeshHandle handle)
196	{
197	  boost::mutex::scoped_lock _(meshes_mutex_);
198	  FilterJob<bool>* remover = new FilterJob<bool>(boost::bind(&MeshFilterBase::removeMeshHelper, this, handle));
199	  JobPtr job(remover);
200	  addJob(job);
201	  job->wait();
202	 
203	  if (!remover->getResult())
204	    throw std::runtime_error("Could not remove mesh. Mesh not found!");
205	  min_handle_ = std::min(handle, min_handle_);
206	}
```
上記のソースの198行目、および203～204行目からgetResult()はboolで判定を行っていると考えられます。また、204行目では例外を投げています。

**Comment by k-hazama-esol** [comment]
`result_`を`ReturnType()`で初期化した場合、198行目で`ReturnType = bool`となるため、初期値は`result_ = false`となる。もし初期値のまま処理が進んでも、203行目の条件分岐で204行目に移行し
例外が発生するため、`ReturnType()`で初期化を行っても問題ない。

**Comment by r-kurose** [comment]
レビュー結果の確認完了
