### ISSUE TITLE
【産総研】【対応対象外】リソースリークの可能性(getSharedStroage())

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#47]
- 指摘カテゴリ:リソースリーク
- チェッカー:RH.LEAK
- 指摘重要度:エラー
- 対象ソース:
moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp
```
62 SharedStorage& getSharedStorage()
63 {
64 #if 0  // destruction of static storage interferes with static destruction in class_loader
65   // More specifically, class_loader's static variables might be already destroyed
66   // while being accessed again in the destructor of the class_loader-based kinematics plugin.
67   static SharedStorage storage;
68   return storage;
69 #else  // thus avoid destruction at all (until class_loader is fixed)
70   static SharedStorage* storage = new SharedStorage;
71   return *storage;
72 #endif
73 }
```
70行目で確保した動的メモリを解放せずに71行目でreturnしているためメモリリークの指摘が出ている。
64～66行目および69行目のコメントより、class_loaderでのメモリ解放の重複を避けるための暫定的な処置であることが分かる。
また、class_loaderはmoveit外部のライブラリに属するので修正できない。よって修正は必要ないと考える。

**Comment by KazukiHazama** [comment]
現在この件に関してKlocworkサポートに問い合わせ中です

**Comment by r-kurose** [comment]
@KazukiHazama 
修正しなくても処理上問題無いことの記述がありません。

**Comment by k-hazama-esol** [comment]
【修正しない理由】
ヒープ領域でメモリを確保しており、プロセス終了時にOSが不要な領域を解放するため、処理上の問題はない。

**Comment by r-kurose** [comment]
本件は修正できない。
