### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード(moveit_experimental)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#5]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.MUST
- 指摘重要度:重大
- パッケージ
   Tag 0.9.15:moveit_experimental（collision_distance_field）
   kinetic-devel:moveit_core（collision_distance_field）

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックする。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
