### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード(moveit_setup_assistant)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#7]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.CALL.MUST,NPD.FUNC.MUST,NPD.FUNC.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_setup_assistant

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックする。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
