### ISSUE TITLE
【産総研】【要対応】逆参照される可能性のあるポインタ変数(moveit_setup_assistant)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#8]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.GEN.MIGHT,NPD.GEN.CALL.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_setup_assistant

逆参照される可能性のあるポインタ変数をnullptrで初期化し、逆参照される可能性のあるコードの直前でNULLチェックを行う。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
