### ISSUE TITLE
【産総研】【要対応】NULL参照する可能性のあるコード(moveit_core)

### ISSUE THREAD

**Issue by k-hazama-esol** [robo-marc/moveit#9]
- 指摘カテゴリ:NULLポインタの逆参照
- チェッカー:NPD.FUNC.MUST,NPD.FUNC.MIGHT
- 指摘重要度:重大
- パッケージ:moveit_core(distance_field,robot_state,robot_model)

NULLポインタが返却される可能性のある関数の戻り値をNULLチェックする。 あるいは、指摘箇所で呼ばれている関数内でNULLチェックする。

**Comment by r-kurose** [comment]
2020-01-23 レビュー完了
